### ISSUE TITLE
i am using gitbash

### ISSUE THREAD

**Issue by webbrowser11** [Alejandrix2456github/Tabiva#1]
Graham@grahamspc MINGW64 ~/tabiva (main)
$ pip install PyQtWebViewEngine
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement PyQtWebViewEngine (from versions: none)
ERROR: No matching distribution found for PyQtWebViewEngine

does this seem weird to you?

**Comment by webbrowser11** [comment]
i think it should be PyQtWebEngine

**Comment by webbrowser11** [comment]
lemme try that

**Comment by Alejandrix2456github** [comment]
srry it was a mistake i forgor about that module does not exsist

**Comment by Alejandrix2456github** [comment]
i think we must add addons,themes and more to tabiva being collaborators

**Comment by webbrowser11** [comment]
okay

**Comment by webbrowser11** [comment]
fir now just merge that pull request i made

**Comment by Alejandrix2456github** [comment]
merged it :)

**Comment by webbrowser11** [comment]
k
